//  Copyright 2020 Insolar Network Ltd.
//  All rights reserved.
//  This material is licensed under the Insolar License version 1.0,
//  available at https://github.com/insolar/testrail-cli/LICENSE.md.

package text

import "github.com/insolar/testrail-cli/source"

var expectedLog = []source.TestEvent{
	{Action: "output", Package: "github.com/insolar/testrail-cli", Test: "", Elapsed: 0.000000, Output: "?   \tgithub.com/insolar/testrail-cli\t[no test files]\n"},
	{Action: "skip", Package: "github.com/insolar/testrail-cli", Test: "", Elapsed: 0.000000, Output: ""},
	{Action: "output", Package: "github.com/insolar/testrail-cli/cmd/testrail-cli", Test: "", Elapsed: 0.000000, Output: "?   \tgithub.com/insolar/testrail-cli/cmd/testrail-cli\t[no test files]\n"},
	{Action: "skip", Package: "github.com/insolar/testrail-cli/cmd/testrail-cli", Test: "", Elapsed: 0.000000, Output: ""},
	{Action: "run", Package: "github.com/insolar/testrail-cli/package1", Test: "TestExample", Elapsed: 0.000000, Output: ""},
	{Action: "output", Package: "github.com/insolar/testrail-cli/package1", Test: "TestExample", Elapsed: 0.000000, Output: "=== RUN   TestExample\n"},
	{Action: "output", Package: "github.com/insolar/testrail-cli/package1", Test: "TestExample", Elapsed: 0.000000, Output: "=== PAUSE TestExample\n"},
	{Action: "pause", Package: "github.com/insolar/testrail-cli/package1", Test: "TestExample", Elapsed: 0.000000, Output: ""},
	{Action: "run", Package: "github.com/insolar/testrail-cli/package1", Test: "TestExample2", Elapsed: 0.000000, Output: ""},
	{Action: "output", Package: "github.com/insolar/testrail-cli/package1", Test: "TestExample2", Elapsed: 0.000000, Output: "=== RUN   TestExample2\n"},
	{Action: "output", Package: "github.com/insolar/testrail-cli/package1", Test: "TestExample2", Elapsed: 0.000000, Output: "=== PAUSE TestExample2\n"},
	{Action: "pause", Package: "github.com/insolar/testrail-cli/package1", Test: "TestExample2", Elapsed: 0.000000, Output: ""},
	{Action: "run", Package: "github.com/insolar/testrail-cli/package1", Test: "TestExample3", Elapsed: 0.000000, Output: ""},
	{Action: "output", Package: "github.com/insolar/testrail-cli/package1", Test: "TestExample3", Elapsed: 0.000000, Output: "=== RUN   TestExample3\n"},
	{Action: "output", Package: "github.com/insolar/testrail-cli/package1", Test: "TestExample3", Elapsed: 0.000000, Output: "    TestExample3: example_test.go:28: C3607 Skip test\n"},
	{Action: "output", Package: "github.com/insolar/testrail-cli/package1", Test: "TestExample3", Elapsed: 0.000000, Output: "    TestExample3: example_test.go:29: sdfs\n"},
	{Action: "output", Package: "github.com/insolar/testrail-cli/package1", Test: "TestExample3", Elapsed: 0.000000, Output: "--- SKIP: TestExample3 (0.50s)\n"},
	{Action: "skip", Package: "github.com/insolar/testrail-cli/package1", Test: "TestExample3", Elapsed: 0.500000, Output: ""},
	{Action: "run", Package: "github.com/insolar/testrail-cli/package1", Test: "TestMGRGroupCreateWith2Members", Elapsed: 0.000000, Output: ""},
	{Action: "output", Package: "github.com/insolar/testrail-cli/package1", Test: "TestMGRGroupCreateWith2Members", Elapsed: 0.000000, Output: "=== RUN   TestMGRGroupCreateWith2Members\n"},
	{Action: "output", Package: "github.com/insolar/testrail-cli/package1", Test: "TestMGRGroupCreateWith2Members", Elapsed: 0.000000, Output: "=== PAUSE TestMGRGroupCreateWith2Members\n"},
	{Action: "pause", Package: "github.com/insolar/testrail-cli/package1", Test: "TestMGRGroupCreateWith2Members", Elapsed: 0.000000, Output: ""},
	{Action: "run", Package: "github.com/insolar/testrail-cli/package1", Test: "TestMGRGroupCreateCheckEmptySequence", Elapsed: 0.000000, Output: ""},
	{Action: "output", Package: "github.com/insolar/testrail-cli/package1", Test: "TestMGRGroupCreateCheckEmptySequence", Elapsed: 0.000000, Output: "=== RUN   TestMGRGroupCreateCheckEmptySequence\n"},
	{Action: "output", Package: "github.com/insolar/testrail-cli/package1", Test: "TestMGRGroupCreateCheckEmptySequence", Elapsed: 0.000000, Output: "=== PAUSE TestMGRGroupCreateCheckEmptySequence\n"},
	{Action: "pause", Package: "github.com/insolar/testrail-cli/package1", Test: "TestMGRGroupCreateCheckEmptySequence", Elapsed: 0.000000, Output: ""},
	{Action: "cont", Package: "github.com/insolar/testrail-cli/package1", Test: "TestExample", Elapsed: 0.000000, Output: ""},
	{Action: "output", Package: "github.com/insolar/testrail-cli/package1", Test: "TestExample", Elapsed: 0.000000, Output: "=== CONT  TestExample\n"},
	{Action: "cont", Package: "github.com/insolar/testrail-cli/package1", Test: "TestMGRGroupCreateCheckEmptySequence", Elapsed: 0.000000, Output: ""},
	{Action: "output", Package: "github.com/insolar/testrail-cli/package1", Test: "TestMGRGroupCreateCheckEmptySequence", Elapsed: 0.000000, Output: "=== CONT  TestMGRGroupCreateCheckEmptySequence\n"},
	{Action: "run", Package: "github.com/insolar/testrail-cli/package1", Test: "TestMGRGroupCreateCheckEmptySequence/groupGoal=200", Elapsed: 0.000000, Output: ""},
	{Action: "output", Package: "github.com/insolar/testrail-cli/package1", Test: "TestMGRGroupCreateCheckEmptySequence/groupGoal=200", Elapsed: 0.000000, Output: "=== RUN   TestMGRGroupCreateCheckEmptySequence/groupGoal=200\n"},
	{Action: "output", Package: "github.com/insolar/testrail-cli/package1", Test: "TestMGRGroupCreateCheckEmptySequence/groupGoal=200", Elapsed: 0.000000, Output: "    TestMGRGroupCreateCheckEmptySequence/groupGoal=200: example_test.go:47: C3702 Create group of 3 members with groupGoal=200 and check empty sequence\n"},
	{Action: "cont", Package: "github.com/insolar/testrail-cli/package1", Test: "TestMGRGroupCreateWith2Members", Elapsed: 0.000000, Output: ""},
	{Action: "output", Package: "github.com/insolar/testrail-cli/package1", Test: "TestMGRGroupCreateWith2Members", Elapsed: 0.000000, Output: "=== CONT  TestMGRGroupCreateWith2Members\n"},
	{Action: "cont", Package: "github.com/insolar/testrail-cli/package1", Test: "TestExample2", Elapsed: 0.000000, Output: ""},
	{Action: "output", Package: "github.com/insolar/testrail-cli/package1", Test: "TestExample2", Elapsed: 0.000000, Output: "=== CONT  TestExample2\n"},
	{Action: "run", Package: "github.com/insolar/testrail-cli/package1", Test: "TestMGRGroupCreateCheckEmptySequence/groupGoal=300", Elapsed: 0.000000, Output: ""},
	{Action: "output", Package: "github.com/insolar/testrail-cli/package1", Test: "TestMGRGroupCreateCheckEmptySequence/groupGoal=300", Elapsed: 0.000000, Output: "=== RUN   TestMGRGroupCreateCheckEmptySequence/groupGoal=300\n"},
	{Action: "output", Package: "github.com/insolar/testrail-cli/package1", Test: "TestMGRGroupCreateCheckEmptySequence/groupGoal=300", Elapsed: 0.000000, Output: "    TestMGRGroupCreateCheckEmptySequence/groupGoal=300: example_test.go:47: C3704 Create group of 3 members with groupGoal=300 and check empty sequence\n"},
	{Action: "run", Package: "github.com/insolar/testrail-cli/package1", Test: "TestMGRGroupCreateCheckEmptySequence/groupGoal=400", Elapsed: 0.000000, Output: ""},
	{Action: "output", Package: "github.com/insolar/testrail-cli/package1", Test: "TestMGRGroupCreateCheckEmptySequence/groupGoal=400", Elapsed: 0.000000, Output: "=== RUN   TestMGRGroupCreateCheckEmptySequence/groupGoal=400\n"},
	{Action: "output", Package: "github.com/insolar/testrail-cli/package1", Test: "TestMGRGroupCreateCheckEmptySequence/groupGoal=400", Elapsed: 0.000000, Output: "    TestMGRGroupCreateCheckEmptySequence/groupGoal=400: example_test.go:47: C3696 Create group of 3 members with groupGoal=400 and check empty sequence\n"},
	{Action: "output", Package: "github.com/insolar/testrail-cli/package1", Test: "TestMGRGroupCreateCheckEmptySequence", Elapsed: 0.000000, Output: "--- PASS: TestMGRGroupCreateCheckEmptySequence (0.00s)\n"},
	{Action: "output", Package: "github.com/insolar/testrail-cli/package1", Test: "TestMGRGroupCreateCheckEmptySequence/groupGoal=200", Elapsed: 0.000000, Output: "    --- PASS: TestMGRGroupCreateCheckEmptySequence/groupGoal=200 (0.00s)\n"},
	{Action: "pass", Package: "github.com/insolar/testrail-cli/package1", Test: "TestMGRGroupCreateCheckEmptySequence/groupGoal=200", Elapsed: 0.000000, Output: ""},
	{Action: "output", Package: "github.com/insolar/testrail-cli/package1", Test: "TestMGRGroupCreateCheckEmptySequence/groupGoal=300", Elapsed: 0.000000, Output: "    --- PASS: TestMGRGroupCreateCheckEmptySequence/groupGoal=300 (0.00s)\n"},
	{Action: "pass", Package: "github.com/insolar/testrail-cli/package1", Test: "TestMGRGroupCreateCheckEmptySequence/groupGoal=300", Elapsed: 0.000000, Output: ""},
	{Action: "output", Package: "github.com/insolar/testrail-cli/package1", Test: "TestMGRGroupCreateCheckEmptySequence/groupGoal=400", Elapsed: 0.000000, Output: "    --- PASS: TestMGRGroupCreateCheckEmptySequence/groupGoal=400 (0.00s)\n"},
	{Action: "output", Package: "github.com/insolar/testrail-cli/package1", Test: "TestExample", Elapsed: 0.000000, Output: "    TestExample: example_test.go:16: C9999 Pass test\n"},
	{Action: "pass", Package: "github.com/insolar/testrail-cli/package1", Test: "TestMGRGroupCreateCheckEmptySequence/groupGoal=400", Elapsed: 0.000000, Output: ""},
	{Action: "pass", Package: "github.com/insolar/testrail-cli/package1", Test: "TestMGRGroupCreateCheckEmptySequence", Elapsed: 0.000000, Output: ""},
	{Action: "output", Package: "github.com/insolar/testrail-cli/package1", Test: "TestExample", Elapsed: 0.000000, Output: "--- PASS: TestExample (0.10s)\n"},
	{Action: "output", Package: "github.com/insolar/testrail-cli/package1", Test: "TestExample2", Elapsed: 0.000000, Output: "    TestExample2: example_test.go:22: C3606 Fail testsdf\n"},
	{Action: "pass", Package: "github.com/insolar/testrail-cli/package1", Test: "TestExample", Elapsed: 0.100000, Output: ""},
	{Action: "output", Package: "github.com/insolar/testrail-cli/package1", Test: "TestExample2", Elapsed: 0.000000, Output: "--- FAIL: TestExample2 (0.30s)\n"},
	{Action: "output", Package: "github.com/insolar/testrail-cli/package1", Test: "TestMGRGroupCreateWith2Members", Elapsed: 0.000000, Output: "    TestMGRGroupCreateWith2Members: example_test.go:35: C3703 Error creating group of 2 members\n"},
	{Action: "fail", Package: "github.com/insolar/testrail-cli/package1", Test: "TestExample2", Elapsed: 0.300000, Output: ""},
	{Action: "output", Package: "github.com/insolar/testrail-cli/package1", Test: "TestMGRGroupCreateWith2Members", Elapsed: 0.000000, Output: "--- PASS: TestMGRGroupCreateWith2Members (1.00s)\n"},
	{Action: "pass", Package: "github.com/insolar/testrail-cli/package1", Test: "TestMGRGroupCreateWith2Members", Elapsed: 1.000000, Output: ""},
	{Action: "output", Package: "github.com/insolar/testrail-cli/package1", Test: "", Elapsed: 0.000000, Output: "FAIL\tgithub.com/insolar/testrail-cli/package1\t1.581s\n"},
	{Action: "fail", Package: "github.com/insolar/testrail-cli/package1", Test: "", Elapsed: 1.581, Output: ""},
	{Action: "output", Package: "github.com/insolar/testrail-cli/source", Test: "", Elapsed: 0.000000, Output: "?   \tgithub.com/insolar/testrail-cli/source\t[no test files]\n"},
	{Action: "skip", Package: "github.com/insolar/testrail-cli/source", Test: "", Elapsed: 0.000000, Output: ""},
	{Action: "run", Package: "github.com/insolar/testrail-cli/source/json", Test: "TestParser_Parse", Elapsed: 0.000000, Output: ""},
	{Action: "output", Package: "github.com/insolar/testrail-cli/source/json", Test: "TestParser_Parse", Elapsed: 0.000000, Output: "=== RUN   TestParser_Parse\n"},
	{Action: "output", Package: "github.com/insolar/testrail-cli/source/json", Test: "TestParser_Parse", Elapsed: 0.000000, Output: "--- PASS: TestParser_Parse (0.00s)\n"},
	{Action: "output", Package: "github.com/insolar/testrail-cli/source/json", Test: "", Elapsed: 0.000000, Output: "PASS\n"},
	{Action: "pass", Package: "github.com/insolar/testrail-cli/source/json", Test: "TestParser_Parse", Elapsed: 0.000000, Output: ""},
	{Action: "output", Package: "github.com/insolar/testrail-cli/source/json", Test: "", Elapsed: 0.000000, Output: "ok  \tgithub.com/insolar/testrail-cli/source/json\t(cached)\n"},
	{Action: "pass", Package: "github.com/insolar/testrail-cli/source/json", Test: "", Elapsed: 0.000000, Output: ""},
	{Action: "run", Package: "github.com/insolar/testrail-cli/source/text", Test: "TestParser_Parse", Elapsed: 0.000000, Output: ""},
	{Action: "output", Package: "github.com/insolar/testrail-cli/source/text", Test: "TestParser_Parse", Elapsed: 0.000000, Output: "=== RUN   TestParser_Parse\n"},
	{Action: "output", Package: "github.com/insolar/testrail-cli/source/text", Test: "TestParser_Parse", Elapsed: 0.000000, Output: "--- PASS: TestParser_Parse (0.00s)\n"},
	{Action: "output", Package: "github.com/insolar/testrail-cli/source/text", Test: "", Elapsed: 0.000000, Output: "PASS\n"},
	{Action: "pass", Package: "github.com/insolar/testrail-cli/source/text", Test: "TestParser_Parse", Elapsed: 0.000000, Output: ""},
	{Action: "output", Package: "github.com/insolar/testrail-cli/source/text", Test: "", Elapsed: 0.000000, Output: "ok  \tgithub.com/insolar/testrail-cli/source/text\t0.200s\n"},
	{Action: "pass", Package: "github.com/insolar/testrail-cli/source/text", Test: "", Elapsed: 0.2, Output: ""},
}
